"""TRLC export — write requirements in BMW's TRLC format.

TRLC (Treat Requirements Like Code) is a DSL for structured requirements
with types, references, and static analysis capabilities. Our exporter
generates .trlc files from specification elements.

TRLC format example:
    package my_project

    requirement REQ-001 "Login Page" {
        description = "Handles user login\\nWith password"
        parent = MOD-001
        tags = ["security", "auth"]
        derived_from = SRC-001
    }
"""

from pathlib import Path

from src.storage.models import Element


def trlc_escape(text: str) -> str:
    """Escape a string for TRLC double-quoted strings.

    Escapes: backslash, double-quote, newline.
    """
    if not text:
        return ""
    return text.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")


def element_to_trlc(element: Element) -> str:
    """Convert a single Element to TRLC format.

    Maps element_type → TRLC type name.
    Includes: id, title, description (content), parent, children,
    tags, derived_from, covered_by.
    """
    trlc_type = element.element_type

    lines = [
        f'{trlc_type} {element.id} "{trlc_escape(element.title)}" {{',
    ]

    # Description from content
    if element.content:
        lines.append(f'    description = "{trlc_escape(element.content)}"')

    # Status
    lines.append(f'    status = "{element.status.value}"')

    # Structural relationships
    if element.parent:
        lines.append(f"    parent = {element.parent}")

    if element.children:
        child_list = ", ".join(element.children)
        lines.append(f"    children = [{child_list}]")

    # Tags
    if element.tags:
        tag_list = ", ".join(f'"{t}"' for t in element.tags)
        lines.append(f"    tags = [{tag_list}]")

    # Traceability
    if element.derived_from:
        src_list = ", ".join(element.derived_from)
        lines.append(f"    derived_from = [{src_list}]")

    if element.covered_by:
        cov_list = ", ".join(element.covered_by)
        lines.append(f"    covered_by = [{cov_list}]")

    # Aspect
    lines.append(f'    aspect = "{element.aspect}"')

    lines.append("}")
    return "\n".join(lines)


class TRLCExporter:
    """Exports specification elements to .trlc files."""

    def __init__(self, package_name: str = "specification"):
        self._package_name = package_name

    def export(self, elements: list[Element], output_path: Path) -> None:
        """Write elements to a .trlc file.

        Args:
            elements: Specification elements to export
            output_path: Where to write the .trlc file
        """
        output_path.parent.mkdir(parents=True, exist_ok=True)

        lines = [
            f"// Generated by Spec Editor — TRLC export",
            f"// {len(elements)} elements",
            f"",
            f"package {self._package_name}",
            f"",
        ]

        for element in elements:
            lines.append(element_to_trlc(element))
            lines.append("")  # blank line between elements

        output_path.write_text("\n".join(lines), encoding="utf-8")

    def export_to_string(self, elements: list[Element]) -> str:
        """Export elements to a TRLC string (for testing/inspection)."""
        parts = [
            f"// Generated by Spec Editor — TRLC export",
            f"// {len(elements)} elements",
            f"",
            f"package {self._package_name}",
            f"",
        ]
        for element in elements:
            parts.append(element_to_trlc(element))
            parts.append("")
        return "\n".join(parts)
