"""Architecture Enforcement — Layer 3 of the Implementation Framework.

Generates and runs architecture compliance tests that verify generated
code follows the declared architectural pattern. Acts as a CI safety net
for LLM-generated code.

Uses **pytest-arch** (``pytest-arch``) or **import-linter** for
dependency rule checking. Can also generate raw ``pytest`` assertions.

Backends:
    - ``pytest_arch`` — pytest-arch plugin (Python dependency rules)
    - ``import_linter`` — import-linter contracts (YAML-based, more expressive)
    - ``pytest`` — plain pytest assertions (simplest, no extra deps)
    - ``none`` — no enforcement (skip architecture checks)

Usage::

    from src.implementation.enforcement import create_arch_enforcer

    enforcer = create_arch_enforcer(project_path)
    violations = enforcer.check(project_path)
    if violations:
        for v in violations:
            print(f"ARCH VIOLATION: {v}")
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass
from pathlib import Path
from typing import Any


@dataclass
class ArchViolation:
    """An architecture rule violation."""

    rule: str
    file: str
    description: str
    severity: str = "error"  # error | warning


class ArchEnforcer(ABC):
    """Abstract architecture enforcement backend.

    Checks that generated code follows the declared architectural pattern.
    """

    @abstractmethod
    def generate_rules(
        self,
        pattern: Any,  # ArchPattern
        project_path: Path,
    ) -> str:
        """Generate architecture test file content.

        Returns the content of a test file (e.g. ``tests/arch/test_architecture.py``)
        that should be written to the project and run in CI.
        """
        ...

    @abstractmethod
    def check(self, project_path: Path) -> list[ArchViolation]:
        """Run architecture checks and return violations.

        Returns empty list if all checks pass.
        """
        ...


# ── Backend implementations ────────────────────────────────────────


class PytestArchEnforcer(ArchEnforcer):
    """Architecture enforcement via pytest-arch plugin.

    Generates ``tests/arch/test_architecture.py`` with ArchRule assertions.
    Requires ``pytest-arch`` package.
    """

    def generate_rules(
        self,
        pattern: Any,
        project_path: Path,
    ) -> str:
        """Generate a pytest-arch test file from pattern dependency rules."""
        rules = pattern.get_dependency_rules()
        pattern_name = pattern.name if hasattr(pattern, "name") else "unknown"

        lines = [
            '"""Auto-generated architecture compliance tests.',
            "",
            f"Pattern: {pattern_name}",
            f"Generated by spec-editor Implementation Framework.",
            '"""',
            "",
            "import pytest",
            "",
            "try:",
            "    from pytest_arch import ArchRule",
            "except ImportError:",
            "    pytest.skip(",
            '        "pytest-arch not installed. Install with: pip install pytest-arch",',
            "        allow_module_level=True,",
            "    )",
            "",
        ]

        for i, rule in enumerate(rules):
            from_path = rule["from_path"]
            forbidden = rule["should_not_import"]
            desc = rule.get("description", f"Rule {i + 1}")

            lines.append("")
            lines.append(f"def test_arch_rule_{i + 1:03d}():")
            lines.append(f'    """{desc}"""')
            lines.append(
                f'    ArchRule("{from_path}")'
            )
            import_list = ', '.join(f'"{f}"' for f in forbidden)
            lines.append(f"        .should_not_import({import_list})")
            lines.append(f'        .check("{project_path}")')

        return "\n".join(lines) + "\n"

    def check(self, project_path: Path) -> list[ArchViolation]:
        """Run pytest-arch checks via subprocess."""
        import subprocess
        import sys
        import json

        test_file = project_path / "tests" / "arch" / "test_architecture.py"
        if not test_file.exists():
            return []

        try:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", str(test_file), "-q", "--tb=line"],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=str(project_path),
            )
            violations: list[ArchViolation] = []
            if result.returncode != 0:
                for line in result.stdout.splitlines():
                    if "FAILED" in line or "ERROR" in line:
                        parts = line.split("::")
                        file_part = parts[0] if parts else ""
                        desc = parts[-1] if len(parts) > 1 else line
                        violations.append(
                            ArchViolation(
                                rule="depends_on",
                                file=file_part,
                                description=desc.strip(),
                            )
                        )
            return violations
        except Exception:
            return []


class ImportLinterEnforcer(ArchEnforcer):
    """Architecture enforcement via import-linter.

    Generates ``.importlinter`` contract files and runs ``lint-imports``.
    Requires ``import-linter`` package.
    """

    def generate_rules(
        self,
        pattern: Any,
        project_path: Path,
    ) -> str:
        """Generate import-linter contract YAML from pattern rules."""
        import yaml

        rules = pattern.get_dependency_rules()
        pattern_name = pattern.name if hasattr(pattern, "name") else "unknown"

        contract: dict[str, Any] = {
            "name": f"spec-editor-{pattern_name}",
            "description": f"Auto-generated import rules for {pattern_name} architecture",
            "layers": [],
            "contracts": [],
        }

        for rule in rules:
            from_path = rule["from_path"]
            forbidden = rule["should_not_import"]
            desc = rule.get("description", "")

            # Create a layer for the source
            layer_name = from_path.replace("/", "_").replace("*", "").strip("_")
            contract["layers"].append({
                "name": layer_name,
                "modules": [from_path],
            })

            # Create independent layers for each forbidden dep
            for f in forbidden:
                f_name = f.replace("/", "_").replace("*", "").strip("_")
                contract["layers"].append({
                    "name": f_name,
                    "modules": [f],
                })
                contract["contracts"].append({
                    "name": f"{layer_name}_must_not_import_{f_name}",
                    "type": "forbidden",
                    "description": desc,
                    "source": layer_name,
                    "forbidden": [f_name],
                })

        return yaml.dump(contract, default_flow_style=False, sort_keys=False)

    def check(self, project_path: Path) -> list[ArchViolation]:
        import subprocess
        import sys

        contract_file = project_path / ".importlinter"
        if not contract_file.exists():
            return []

        try:
            result = subprocess.run(
                [sys.executable, "-m", "importlinter", "lint"],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=str(project_path),
            )
            violations: list[ArchViolation] = []
            if result.returncode != 0:
                for line in result.stdout.splitlines():
                    if "forbidden" in line.lower() or "violation" in line.lower():
                        violations.append(
                            ArchViolation(
                                rule="forbidden_import",
                                file="",
                                description=line.strip(),
                            )
                        )
            return violations
        except Exception:
            return []


class PytestPlainEnforcer(ArchEnforcer):
    """Plain pytest assertions for architecture enforcement.

    No extra dependencies — generates standard pytest tests
    that check import rules using Python's ``ast`` module.
    """

    def generate_rules(
        self,
        pattern: Any,
        project_path: Path,
    ) -> str:
        """Generate plain pytest test file with AST-based import checks."""
        rules = pattern.get_dependency_rules()
        pattern_name = pattern.name if hasattr(pattern, "name") else "unknown"

        lines = [
            '"""Auto-generated architecture compliance tests.',
            "",
            f"Pattern: {pattern_name}",
            f"Generated by spec-editor Implementation Framework.",
            "Checks import dependencies using AST parsing.",
            '"""',
            "",
            "import ast",
            "import sys",
            "from pathlib import Path",
            "from collections import defaultdict",
            "",
            "",
            "def _collect_imports(filepath: str) -> set[str]:",
            '    """Extract all imported module names from a Python file using AST."""',
            "    try:",
            "        with open(filepath) as f:",
            "            tree = ast.parse(f.read())",
            "    except (SyntaxError, UnicodeDecodeError):",
            "        return set()",
            "",
            "    imports = set()",
            "    for node in ast.walk(tree):",
            "        if isinstance(node, ast.Import):",
            "            for alias in node.names:",
            "                imports.add(alias.name.split('.')[0])",
            "        elif isinstance(node, ast.ImportFrom):",
            "            if node.module:",
            "                imports.add(node.module.split('.')[0])",
            "    return imports",
            "",
            "",
            "PROJECT_ROOT = Path(__file__).resolve().parents[2]",
            "",
        ]

        for i, rule in enumerate(rules):
            from_path = rule["from_path"]
            forbidden = rule["should_not_import"]
            desc = rule.get("description", f"Rule {i + 1}")

            lines.append("")
            lines.append(f"def test_arch_rule_{i + 1:03d}():")
            lines.append(f'    """{desc}"""')
            lines.append(f"    src_dir = PROJECT_ROOT")
            lines.append(f"    forbidden = {forbidden!r}")
            lines.append("")
            lines.append("    violations = []")
            lines.append(f"    for pyfile in src_dir.glob('{from_path}.py'):")
            lines.append("        imports = _collect_imports(str(pyfile))")
            lines.append("        for imp in imports:")
            lines.append("            for f in forbidden:")
            lines.append("                if imp.startswith(f.replace('/', '.').strip('.')):")
            lines.append("                    violations.append(f'{pyfile.relative_to(PROJECT_ROOT)} imports {imp} (forbidden: {f})')")
            lines.append("")
            lines.append("    assert len(violations) == 0, (")
            lines.append('        "Architecture violations found:\\\\n" + "\\\\n".join(violations)')
            lines.append("    )")

        return "\n".join(lines) + "\n"

    def check(self, project_path: Path) -> list[ArchViolation]:
        import subprocess
        import sys

        test_file = project_path / "tests" / "arch" / "test_architecture.py"
        if not test_file.exists():
            return []

        try:
            result = subprocess.run(
                [sys.executable, "-m", "pytest", str(test_file), "-q", "--tb=short"],
                capture_output=True,
                text=True,
                timeout=60,
                cwd=str(project_path),
            )
            violations: list[ArchViolation] = []
            if result.returncode != 0:
                for line in result.stdout.splitlines():
                    if "Architecture violations" in line:
                        violations.append(
                            ArchViolation(
                                rule="depends_on",
                                file="",
                                description=line.strip(),
                            )
                        )
            return violations
        except Exception:
            return []


class NoopEnforcer(ArchEnforcer):
    """No architecture enforcement — skip all checks."""

    def generate_rules(
        self,
        pattern: Any,
        project_path: Path,
    ) -> str:
        return (
            '"""No architecture enforcement configured."""\n'
            "# spec-editor: architecture enforcement disabled\n"
        )

    def check(self, project_path: Path) -> list[ArchViolation]:
        return []


# ── Factory ─────────────────────────────────────────────────────────


def create_arch_enforcer(project_path: str | Path) -> ArchEnforcer:
    """Create an ArchEnforcer from project configuration.

    Reads ``local.yaml`` → ``enforcement:`` section:

    .. code-block:: yaml

        enforcement:
          backend: pytest          # pytest | pytest_arch | import_linter | none
          strict: true             # fail CI on violations (default: true)
          auto_generate: true      # auto-generate test files (default: true)

    Falls back to ``pytest`` (plain AST checks, no extra deps).
    """
    import os

    proj = Path(project_path)
    backend_name = "pytest"

    local_yaml = proj / "local.yaml"
    if local_yaml.exists():
        try:
            import yaml

            data = yaml.safe_load(local_yaml.read_text()) or {}
            enf_cfg = data.get("enforcement", {})
            backend_name = enf_cfg.get("backend", "pytest")
        except Exception:
            pass

    backend_name = os.environ.get("SPEC_EDITOR__ENFORCEMENT_BACKEND", backend_name)

    if backend_name == "pytest_arch":
        return PytestArchEnforcer()
    elif backend_name == "import_linter":
        return ImportLinterEnforcer()
    elif backend_name == "none":
        return NoopEnforcer()
    else:
        return PytestPlainEnforcer()
