#!/bin/bash
# Spec Editor quick demo.
# Requires: spec-editor (pip install spec-editor)
# Usage: bash docs/demo.sh

set -e

echo "========================================="
echo "  Spec Editor — Quick Demo"
echo "========================================="
echo ""

# 1. Install (skip if already done)
echo "==> 1. Install"
echo "$ pip install spec-editor"
echo ""

# 2. Create project
echo "==> 2. Create project with example"
echo "$ spec-editor init my-project --with-example"
spec-editor init /tmp/spec-demo --with-example 2>&1 | tail -5
echo ""

# 3. Show what's inside
echo "==> 3. What's inside?"
echo "$ ls my-project/"
echo "  source/     — requirements document"
echo "  aspects/    — structured spec (generated by agents)"
echo "  methodology.yaml"
echo "  agents.yaml"
echo ""

echo "$ cat my-project/source/readme.md | head -8"
head -8 /tmp/spec-demo/source/readme.md
echo "  ..."
echo ""

# 4. Demo mode (no API key needed)
echo "==> 4. Quick demo (no API key)"
echo "$ spec-editor demo"
spec-editor demo -o /tmp/spec-demo-quick 2>&1 | tail -8
echo ""

# 5. Validate
echo "==> 5. Validate the spec"
echo "$ spec-editor validate -p /tmp/spec-demo-quick"
spec-editor validate -p /tmp/spec-demo-quick 2>&1 | grep -v debug
echo ""

# 6. Context for AI coding
echo "==> 6. Build context for AI coding assistant"
echo "$ spec-editor context -p /tmp/spec-demo-quick -e MOD-001"
spec-editor context -p /tmp/spec-demo-quick -e MOD-001 2>&1 | grep -v debug | head -10
echo "  ..."
echo ""

echo "========================================="
echo "  Done! Try: spec-editor run"
echo "  (requires DEEPSEEK_API_KEY in .env)"
echo "========================================="
