package com.speceditor.actions

import com.intellij.openapi.actionSystem.AnAction
import com.intellij.openapi.actionSystem.AnActionEvent
import com.intellij.openapi.ui.Messages
import com.speceditor.SpecEditorProjectService
import com.speceditor.mcp.McpClient
import com.google.gson.JsonParser

/**
 * Creates a new spec element via MCP.
 *
 * Opens a series of input dialogs:
 * 1. Select aspect
 * 2. Enter title
 * The element ID is auto-generated by the MCP server.
 */
class CreateElementAction : AnAction() {

    override fun actionPerformed(e: AnActionEvent) {
        val project = e.project ?: return
        val service = SpecEditorProjectService.getInstance(project)

        if (service.projectPath == null) {
            Messages.showInfoMessage(project, "No spec-editor project open.", "Spec Editor")
            return
        }

        try {
            val client = McpClient("http://127.0.0.1:${service.mcpPort}/mcp")

            // Get methodology for aspect list
            val methodResult = client.callTool("get_methodology", emptyMap())
            val methodText = methodResult.getAsJsonArray("content")
                ?.get(0)?.asJsonObject?.get("text")?.asString ?: "{}"
            val methodData = JsonParser.parseString(methodText).asJsonObject
            val aspects = methodData.getAsJsonArray("aspects")
                ?.map { it.asJsonObject.get("name").asString } ?: listOf(
                "modules", "user_scenarios", "user_interface",
                "data_entities", "nfr", "implementation", "metrics", "sources"
            )

            // Select aspect
            val aspect = Messages.showEditableChooseDialog(
                "Select aspect for the new element:",
                "Create Element — Aspect",
                Messages.getQuestionIcon(),
                aspects.toTypedArray(),
                aspects.firstOrNull() ?: "modules",
                null
            ) ?: return

            // Enter title
            val title = Messages.showInputDialog(
                project,
                "Enter element title:",
                "Create Element — Title",
                Messages.getQuestionIcon()
            ) ?: return

            // Determine element type from methodology
            val elementType = try {
                val asp = methodData.getAsJsonArray("aspects")
                    ?.find { it.asJsonObject.get("name").asString == aspect }
                asp?.asJsonObject?.getAsJsonArray("element_types")
                    ?.get(0)?.asJsonObject?.get("name")?.asString ?: "module"
            } catch (_: Exception) { "module" }

            // Create via MCP
            val result = client.callTool("write_element", mapOf(
                "aspect" to aspect,
                "element_type" to elementType,
                "id" to "",  // auto-generated
                "title" to title,
                "content" to ""
            ))
            val resultText = result.getAsJsonArray("content")
                ?.get(0)?.asJsonObject?.get("text")?.asString ?: "{}"
            val resultData = JsonParser.parseString(resultText).asJsonObject
            val generatedId = resultData.get("element_id")?.asString ?: "unknown"

            Messages.showInfoMessage(
                project,
                "Element created: $generatedId ($aspect)",
                "Spec Editor"
            )

            // Notify tool window to refresh
            notifyFrontend(project, "elementsChanged")

        } catch (ex: Exception) {
            Messages.showErrorDialog(
                project,
                "Failed to create element: ${ex.message}",
                "Spec Editor"
            )
        }
    }

    override fun update(e: AnActionEvent) {
        val project = e.project
        e.presentation.isEnabled = project != null &&
            SpecEditorProjectService.getInstance(project).projectPath != null &&
            SpecEditorProjectService.getInstance(project).isMcpRunning
    }

    companion object {
        fun notifyFrontend(project: com.intellij.openapi.project.Project, event: String) {
            // The frontend is in a JCEF browser — we signal through
            // a custom property that the reload handler picks up.
            // For now, user can manually refresh the tool window.
        }
    }
}
